### ISSUE TITLE
RopenCVLite showing installation error.

### ISSUE THREAD

**Issue by mallick84** [swarm-lab/ROpenCVLite#11]
Hi,
 I am using Rstudio 3.5.1. 64 bit on window 7. My cmake version is 3.12.2. While installing cmake I have added to my path. Installing RopenCVLite I have found following error

`source("https://neuroconductor.org/neurocLite.R")
neuro_install('ROpenCVLite', release = "stable", release_repo = "github")

opencv-3.4.0/samples/wp8/readme.txt
+ cp ../cap_dshow.cpp opencv-3.4.0/modules/videoio/src/
+ cd opencv-3.4.0
+ [ -d C:/MANUAL~1/R-35~1.1/bin/x64 ]
+ mkdir build64
+ cd build64
+ cmake -G Unix Makefiles -DCMAKE_C_COMPILER=C:/Rtools/mingw_64/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Rtools/mingw_64/bin/g++.exe -DCMAKE_RC_COMPILER=C:/Rtools/mingw_64/bin/windres.exe -DCMAKE_MAKE_PROGRAM=C:/Rtools/bin/make.exe -DENABLE_PRECOMPILED_HEADERS=OFF -DBUILD_opencv_world=OFF -DBUILD_opencv_contrib_world=OFF -DBUILD_matlab=OFF -DPYTHON_EXECUTABLE=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=../../../opencv/ ../
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:117 (project):
  The CMAKE_CXX_COMPILER:

    C:/Rtools/mingw_64/bin/g++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:117 (project):
  The CMAKE_C_COMPILER:

    C:/Rtools/mingw_64/bin/gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Users/dell/AppData/Local/Temp/RtmpIxnXKm/devtools1f206403159f/neuroconductor-ROpenCVLite-9354d11/inst/tmp/opencv-3.4.0/build64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/dell/AppData/Local/Temp/RtmpIxnXKm/devtools1f206403159f/neuroconductor-ROpenCVLite-9354d11/inst/tmp/opencv-3.4.0/build64/CMakeFiles/CMakeError.log".
ERROR: configuration failed for package 'ROpenCVLite'
* removing 'C:/Manually saved/R-3.5.1/library/ROpenCVLite'
In R CMD INSTALL
Installation failed: Command failed (1)
Error in neuro_install("ROpenCVLite", release = "stable", release_repo = "github") : 
  Installation failed, please try with upgrade_dependencies = TRUE
Called from: neuro_install("ROpenCVLite", release = "stable", 
    release_repo = "github")`

Please provide me with some suggestion link

**Comment by sjmgarnier** [comment]
@mallick84 Looks like you didn't install Rtools.

**Comment by sjmgarnier** [comment]
@mallick84 Where is it installed? ROpenCVLite looks for it at `C:/Rtools`. If it's installed anywhere else, the package won't find it (at least at the moment).

**Comment by mallick84** [comment]
@sjmgarnier , Thank you for your reply. I will check it and reply soon.

**Comment by mallick84** [comment]
@sjmgarnier, Thank you. I was trying this for one week. I thought it might be the problem of cmake installation which is not able to find the compiler. 

with your suggestion, I could able to solve the issue.

Yes, it was the problem of Rtools installation.  Actually in my `path`, one more previously installed Rtools was available, which was creating problems. 

What did I do?
First I uninstall the Rtools and then deletes all the Rtools history files from the `C drive`. I delete also the Rtools path of the previous version, Then I install freshly Rtools 3.4 and I chose the location as `C:Rtools. `

I restart R and then I could able to install RopenCVLite.

Thank you @sjmgarnier .
