### ISSUE TITLE
Windows Installation Error

### ISSUE THREAD

**Issue by jdknguyen** [swarm-lab/ROpenCVLite#13]
Hi,

I am trying to install ROpenCVLite on my computer and am running into an error. I am using R 3.5.1, CMake 3.13.2, and Rtools 3.4. R is at C:/Program Files/R/R-3.5.1,CMake is at C:/Program Files/CMake, and Rtools is at C:/Rtools. All have been added to the system path. It appears to install the 64-bit version properly but has issues installing the 32-bit one. Any help would be greatly appreciated.

The log for the error is below:

+ cd ../
+ [ -d C:/PROGRA~1/R/R-35~1.1/bin/i386 ]
+ mkdir build32
+ cd build32
+ cmake -G Unix Makefiles -DCMAKE_C_COMPILER=C:/Rtools/mingw_32/bin/gcc.exe -DCMAKE_CXX_COMPILER=C:/Rtools/mingw_32/bin/g++.exe -DCMAKE_RC_COMPILER=C:/Rtools/mingw_32/bin/windres.exe -DCMAKE_MAKE_PROGRAM=C:/Rtools/bin/make.exe -DENABLE_PRECOMPILED_HEADERS=OFF -DENABLE_CXX11=ON -DBUILD_opencv_world=OFF -DBUILD_opencv_contrib_world=OFF -DBUILD_matlab=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DWITH_MSMF=OFF -DBUILD_PROTOBUF=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=../../../inst/opencv/ ../
-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:127 (project):
  The CMAKE_CXX_COMPILER:

    C:/Rtools/mingw_32/bin/g++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:127 (project):
  The CMAKE_C_COMPILER:

    C:/Rtools/mingw_32/bin/gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "C:/Users/joeyd/AppData/Local/Temp/RtmpQ5T7wq/R.INSTALL2af4543d463a/ROpenCVLite/src/opencv-3.4.3/build32/CMakeFiles/CMakeOutput.log".
See also "C:/Users/joeyd/AppData/Local/Temp/RtmpQ5T7wq/R.INSTALL2af4543d463a/ROpenCVLite/src/opencv-3.4.3/build32/CMakeFiles/CMakeError.log".
ERROR: configuration failed for package 'ROpenCVLite'
* removing 'C:/Users/joeyd/OneDrive/Documents/R/win-library/3.5/ROpenCVLite'
* restoring previous 'C:/Users/joeyd/OneDrive/Documents/R/win-library/3.5/ROpenCVLite'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/joeyd/AppData/Local/Temp/RtmpCI8H58/file2d9016e377d8/ROpenCVLite_0.1.34.3.tar.gz’ had non-zero exit status

Thanks,
Joseph

**Comment by jdknguyen** [comment]
@sjmgarnier Thank you for the rapid response. I tried re-installing and making sure to set the path (I am nearly certain that I did this the first time) when the installer prompted me, but got the same result. My system variable PATH is: 

C:\Rtools\bin;c:\Rtools\mingw_64\bin;c:\fftw;c:\Rtools\gcc-4.6.3\bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files (x86)\PerkinElmerInformatics\ChemOffice2016\ChemScript\Lib;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;%SYSTEMROOT%\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MATLAB\R2018a\bin\x64;C:\Program Files\R\R-3.5.1\bin\x64;C:\Program Files\CMake\bin

Please let me know if I am missing something.

**Comment by sjmgarnier** [comment]
@jdknguyen The only difference I find between your toolchains and mine is that I have `c:\Rtools\mingw_32\bin` in my path instead of `c:\Rtools\mingw_64\bin`.

**Comment by jdknguyen** [comment]
@sjmgarnier gotcha. I tried installing the 32-bit compiler as well, which got the installation to work. Thank you for helping!
