### ISSUE TITLE
ROpenCVLite Installation Error

### ISSUE THREAD

**Issue by jdknguyen** [swarm-lab/ROpenCVLite#16]
Hi,

I am currently running into a problem installing ROpenCVLite on my Windows 10 computer. I am using R 3.5.3, RTools 3.4.0.1964, CMake 3.13.5. Any tips would be greatly appreciated.

My path includes the following:
c:\Rtools\bin
c:\Rtools\mingw_64\bin
c:\Rtools\mingw_32\bin
C:\Program Files\CMake\bin
C:\Program Files\R\R-3.5.3\bin

Error Log:

CMake Error at CMakeLists.txt:153 (message):
  CMake fails to determine the bitness of the target platform.

    Please check your CMake and compiler installation. If you are cross-compiling then ensure that your CMake toolchain file correctly sets the compiler details.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Public/Documents/R/win-library/3.5/ROpenCVLite/tmp/opencv-4.1.0/build64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Public/Documents/R/win-library/3.5/ROpenCVLite/tmp/opencv-4.1.0/build64/CMakeFiles/CMakeError.log".
MINGW3~1.EXE: *** No targets specified and no makefile found.  Stop.
MINGW3~1.EXE: *** No rule to make target 'install'.  Stop.
-- The CXX compiler identification is GNU 4.9.3
-- The C compiler identification is GNU 4.9.3
-- Check for working CXX compiler: c:/Rtools/mingw_32/bin/g++.exe
-- Check for working CXX compiler: c:/Rtools/mingw_32/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: c:/Rtools/mingw_32/bin/gcc.exe
-- Check for working C compiler: c:/Rtools/mingw_32/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:153 (message):
  CMake fails to determine the bitness of the target platform.

    Please check your CMake and compiler installation. If you are cross-compiling then ensure that your CMake toolchain file correctly sets the compiler details.

-- Configuring incomplete, errors occurred!
See also "C:/Users/Public/Documents/R/win-library/3.5/ROpenCVLite/tmp/opencv-4.1.0/build32/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Public/Documents/R/win-library/3.5/ROpenCVLite/tmp/opencv-4.1.0/build32/CMakeFiles/CMakeError.log".
MINGW3~1.EXE: *** No targets specified and no makefile found.  Stop.
MINGW3~1.EXE: *** No rule to make target 'install'.  Stop.

Thank you,
Joseph

**Comment by sjmgarnier** [comment]
@jdknguyen I recommend that you try with the latest versions of RTools (3.5) and Cmake (3.14.5).

**Comment by CorradoLanera** [comment]
Using R4.2.0 and RTools42, I get the following error on Windows (Please note that `C:/rtools42/mingw64/bin` exists, but it is empty (as well as all the (sub)folders of `mingw32`, `clang32`, `clang64`, `clangarm64`, `ucrt64`)... I tried to reinstall RTools42 a few times, but those folders are still empty. Is that my issue, or... is it a feature of RTools42? In the last case, you would possibly like to update your installation script [here](https://github.com/swarm-lab/ROpenCVLite/blob/e7774f33718d208233fdd888b2e1dd3e779dc6ec/R/opencv.R#L217-L219)).

```r
> ROpenCVLite::installOpenCV()
OpenCV is not installed on this system. Would you like to install it now? This will take several minutes. 

1: yes
2: no

Selection: 1
OpenCV will be installed in C:\Users\corrado.lanera\AppData\Local\R\win-library\4.2\ROpenCV
Clearing install path.
trying URL 'https://github.com/opencv/opencv/archive/4.5.5.tar.gz'
downloaded 85.7 MB

-- The CXX compiler identification is unknown
-- The C compiler identification is unknown
CMake Error at CMakeLists.txt:113 (enable_language):
  The CMAKE_CXX_COMPILER:

    C:/rtools42/mingw64/bin/g++.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


CMake Error at CMakeLists.txt:113 (enable_language):
  The CMAKE_C_COMPILER:

    C:/rtools42/mingw64/bin/gcc.exe

  is not a full path to an existing compiler tool.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "C:/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64/CMakeFiles/CMakeOutput.log".
See also "C:/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64/CMakeFiles/CMakeError.log".
make: Entering directory '/c/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64'
make: *** No targets specified and no makefile found.  Stop.
make: Leaving directory '/c/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64'
make: Entering directory '/c/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64'
make: *** No rule to make target 'install'.  Stop.
make: Leaving directory '/c/Users/corrado.lanera/AppData/Local/Temp/Rtmpmi8tHS/opencv-4.5.5/build64'
[1] FALSE
```

Thank you!

**Comment by sjmgarnier** [comment]
@CorradoLanera Thanks for this. I haven't checked the package with R 4.2 on Windows yet. I'll do it whenever I can find the time today.

**Comment by sjmgarnier** [comment]
@CorradoLanera I've successfully managed to change the script and compile OpenCV using RTools 4.2. However, there seems to be a problem with locating the DLLs when trying to use them (e.g., after compiling Rvision, loading fails with a `loadLibrary failure: The specified module could not be found` error). I'm not an expert Windows developer, so that might take some time before I can understand and fix the problem. Any help would be appreciated if you have experience with that.

**Comment by CorradoLanera** [comment]
Thank you, @sjmgarnier! Unfortunately, I am not a windows developer at all 😢 I've tried to manage the installation without success. Can you share the modified code (maybe in a secondary branch) so that I can try the installation on my system and provide you additional feedback?

**Comment by sjmgarnier** [comment]
@CorradoLanera Thanks. The end of the semester is nuts at the university, so I may need a little time to get back to this. I'll try to create a branch tomorrow or Tuesday, depending on the available time.

**Comment by CorradoLanera** [comment]
@sjmgarnier I have just successfully installed both ROpenCVLite and Rvision on R 4.2.0 / Win 11
Thank you for your work and time!
