### ISSUE TITLE
Installation broken with Rtools40 / R 4.0.0

### ISSUE THREAD

**Issue by skalteis** [swarm-lab/ROpenCVLite#20]
Hi!

Just to let you know - currently the installation on Windows is broken with Rtools40 / R4.0.0 since the paths to gcc and make in Rtools changed.

"make" is now located in $RTOOLS_HOME\usr\bin\make and the underscore in the mingw32/64 directories has been dropped!

Manually changing R/opencv.R fixed this issue for me.

Thank you for your work & best regards!

EDIT: clarified Windows platform

**Comment by sjmgarnier** [comment]
@skalteis Thanks for this. Windows is the bane of my R life :-) I have to make changes this week to keep ROpenCVLite on CRAN, I will include these changes as well.

**Comment by sjmgarnier** [comment]
@skalteis It looks like it cannot compile in 32-bit anymore (at least I can't figure out how to get the i386 installation folder anymore). Any idea what's up?

**Comment by skalteis** [comment]
Works for me (Windows 10, 64bit) with these hard-coded changes in opencv.R:

`
            if (any(archAvail)) {
                pkgbuild::check_rtools()
                rtoolsPath <- gsub("/bin", "", "C:/rtools40")
                for (i in 1:2) {
                  if (archAvail[i]) {
                    sourceDir <- paste0(tmpDir, "/opencv-4.1.2/")
                    buildDir <- paste0(sourceDir, "build", 
                      arch[i])
                    dir.create(buildDir, showWarnings = FALSE)
                    system(paste0("cmake -G \"Unix Makefiles\" -DCMAKE_C_COMPILER=", 
                      rtoolsPath, "/mingw", arch[i], "/bin/gcc.exe -DCMAKE_CXX_COMPILER=", 
                      rtoolsPath, "/mingw", arch[i], "/bin/g++.exe -DCMAKE_RC_COMPILER=", 
                      rtoolsPath, "/mingw", arch[i], "/bin/windres.exe -DCMAKE_MAKE_PROGRAM=", 
                      rtoolsPath, "/usr/bin","/make.exe -DENABLE_PRECOMPILED_HEADERS=OFF -DENABLE_CXX11=ON -DBUILD_ZLIB=ON -DBUILD_opencv_world=OFF -DBUILD_opencv_contrib_world=OFF -DBUILD_matlab=OFF -DBUILD_opencv_java=OFF -DBUILD_opencv_python2=OFF -DBUILD_opencv_python3=OFF -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DWITH_MSMF=OFF -DBUILD_PROTOBUF=OFF -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=", 
                      openCVPath, " -B", buildDir, " -H", 
                      sourceDir))
                    system(paste0(rtoolsPath, "/usr/bin", "/make.exe -j", 
                      parallel::detectCores(), " -C ", 
                      buildDir))
                    system(paste0(rtoolsPath, "/usr/bin", "/make.exe -C", 
                      buildDir, " install"))
                  }
                }
            }`

Note that I don't rely on pkgbuild::rtools_path() for setting rtoolsPath anymore - it does weird things with double backslashes here. So I ripped it out, works for me.
Of course, this is not a generally applicable solution, especially considering that it should work on systems with both old and new Rtools installations and R versions.

**Comment by sjmgarnier** [comment]
@skalteis This is roughly how I've done it for the new rtools, but the issue is that it does only seem to compile the x64 version. The result of compiling with the 32 bit gcc/g++/etc ends up in the x64 installation directory, not in the x86 as it did before. And that causes big problem when trying to compile anything against OpenCV later (because essentially the 32 bit binaries are not present). Not sure what's up, I'll keep investigating.

**Comment by skalteis** [comment]
Hmmm... I have both a x86 and a x64 directory under opencv in my R library folder, with libraries and binaries. Running opencv_version_win32.exe from each shows that it's compiled with the appropriate compiler for 32-/64-bit arch. Built just an hour ago.

**Comment by sjmgarnier** [comment]
@skalteis Looks like it might be linked to OpenCV 4.3 only. It works with 4.1.2.
