### ISSUE TITLE
ROpenCVLite does not load after installation

### ISSUE THREAD

**Issue by apintar** [swarm-lab/ROpenCVLite#22]
**OS**

64 bit CentOS 8 

**Output of** `sessionInfo()` **from R**

R version 4.0.3 (2020-10-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 8

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.0.3

**Steps to Reproduce**

1. Install ROpenCVLite with `install.packages("ROpenCVLite")`
2. Install OpenCV by loading ROpenCVLite for the first time with `library(ROpenCVLite)`
3. quit R
4. restart R
5. load ROpenCVLite with `library(ROpenCVLite)`
6. The following error is produced

Error: package or namespace load failed for ‘ROpenCVLite’:
 .onAttach failed in attachNamespace() for 'ROpenCVLite', details:
  call: file(file, "rt")
  error: cannot open the connection
In addition: Warning message:
In file(file, "rt") :
  cannot open file '/my/home/R/x86_64-redhat-linux-gnu-library/4.0//opencv/lib/cmake/opencv4/OpenCVConfig-version.cmake': No such file or directory

**Steps to Resolve**

Create the following soft link
`ln -s /my/home/R/x86_64-redhat-linux-gnu-library/4.0/opencv/lib64 /my/home/R/x86_64-redhat-linux-gnu-library/4.0/opencv/lib`

**Comment by sjmgarnier** [comment]
703dec0 and f7a2256 fix this problem. No need to create a soft link anymore.
