### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by cgb09c** [swarm-lab/ROpenCVLite#24]
Hi, 

I am trying to install ROpenCVLite with R 4.1.2 on windows 10.  I have followed the instructions for ROpenCVLite install at (https://swarm-lab.github.io/ROpenCVLite/articles/install.html#installing-ropencvlite).

R4.1.2, Cmake 3.22.2 and Rtools 4.0 are installed on my machine and in the path variable

After downloading the package with
 > install.packages(ROpenCVLite)

 I ran the next command to install

 > library(ROpenCVLite)

and the following Error appears:

Error: package or namespace load failed for ‘ROpenCVLite’:
 .onAttach failed in attachNamespace() for 'ROpenCVLite', details:
  call: system(command, as.integer(flag), f, stdout, stderr, timeout)
  error: character string expected as first argument

Any idea on how to fix? Any help would be much appreciated! @sjmgarnier

**Comment by sjmgarnier** [comment]
@cgb09c I'll need more information. Can you walk me through all the steps that you followed before getting that error? Thanks.

**Comment by cgb09c** [comment]
> @cgb09c I'll need more information. Can you walk me through all the steps that you followed before getting that error? Thanks.

Hello,
I am following up on this request to see if you have any advice on how to resolve this error?

**Comment by sjmgarnier** [comment]
@cgb09c As I said, I need more information. Can you walk me through all the steps that you followed before getting that error? Thanks.

**Comment by cgb09c** [comment]
Sure, I had modified the original post as well not sure if you saw that but I followed the steps in the instruction manual exactly. Is there anything else I should include?

1. Downloaded & ran Cmake installer
2. install.packages("devtools")
3. installr.::install.Rtools()
4. install.packages(ROpenCVLite)
5. library(ROpenCVLite)

OUTPUT:

OpenCV is not installed on this system. Would you like to install it now? This will take several minutes. 

1: yes
2: no

Selection: 1 
OpenCV will be installed in C:/Program Files/R/R-4.1.2/library/opencv
Removing old OpenCV installation.
trying URL 'https://github.com/opencv/opencv/archive/4.5.2.tar.gz'
Content type 'application/x-gzip' length unknown
downloaded 84.8 MB

Error: package or namespace load failed for ‘ROpenCVLite’:
 .onAttach failed in attachNamespace() for 'ROpenCVLite', details:
  call: system(command, as.integer(flag), f, stdout, stderr, timeout)
  error: character string expected as first argument

**Comment by cgb09c** [comment]
Awesome, Thanks Simon! Looks like it got past that error and was able to finish installing although when loading ROpenCVLite, it shows the "OpenCV is not installed on this system" message. RVision install then fails due to the same error. Should I start  new issue?

**Comment by sjmgarnier** [comment]
@cgb09c What happens when you run `ROpenCVLite::installOpenCV()`?

**Comment by sjmgarnier** [comment]
@cgb09c It looks like you haven't compiled and installed OpenCV yet. You need to select 'yes' to make that happen.

**Comment by cgb09c** [comment]
Of course, I have done that a few times already and it goes thru the 15 minute install and all that and completes. There is no error message at the end so it appears it went ok, but again when I try to load the package, it brings me back to that message that it is not installed...

**Comment by sjmgarnier** [comment]
@cgb09c Strange. I wonder if R needs to be restarted on Windows for new folders to be added to the path.

**Comment by sjmgarnier** [comment]
@cgb09c I know that there can be an issue on Windows when there is a space in the path to a folder, like in "Program Files" in your case (see #6, #8, #19, #23), but I thought this was mostly fixed with RTools 4.0 (the fact that you can compile OpenCV is an indication of that).

**Comment by cgb09c** [comment]
Ok thanks for the info. Trust me I would prefer to be working with a linux machine but this particular one is setup such it can't do a dual boot but no worries, it looks like the work around should do the trick!
