### ISSUE TITLE
 install error

### ISSUE THREAD

**Issue by Chengaowei** [swarm-lab/ROpenCVLite#27]
^~~~~~~~~~~
[ 97%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/optflowgf.cpp.obj
[ 97%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/optical_flow_io.cpp.obj
[ 97%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/tracking/detail/tracker_feature.cpp.obj
[ 97%] Building CXX object modules/video/CMakeFiles/opencv_video.dir/src/tracking/detail/tracker_feature_set.cpp.obj
[ 97%] Building CXX object 

......

make[2]: Entering directory '/c/Users/ADMINI~1/AppData/Local/Temp/RtmpoFFfIa/opencv-4.6.0/build64'
make[2]: Leaving directory '/c/Users/ADMINI~1/AppData/Local/Temp/RtmpoFFfIa/opencv-4.6.0/build64'
[100%] Built target opencv_version_win32
make[1]: Leaving directory '/c/Users/ADMINI~1/AppData/Local/Temp/RtmpoFFfIa/opencv-4.6.0/build64'
Install the project...
-- Install configuration: "RELEASE"
-- Installing: C:/Program/etc/licenses/opencl-headers-LICENSE.txt
-- Installing: C:/Program/etc/licenses/ffmpeg-license.txt
-- Installing: C:/Program/etc/licenses/ffmpeg-readme.txt
-- Installing: C:/Program/include/opencv2/cvconfig.h
.........................
-- Installing: C:/Program/x64/mingw/lib/libopencv_objdetect460.dll.a
-- Installing: C:/Program/x64/mingw/bin/libopencv_objdetect460.dll

-- Installing: C:/Program/x64/mingw/bin/opencv_version_win32.exe
make: Leaving directory '/c/Users/ADMINI~1/AppData/Local/Temp/RtmpoFFfIa/opencv-4.6.0/build64'
Warning message:
In if (!grepl("40", pkgbuild::rtools_path())) { :
  the condition has length > 1 and only the first element will be used

After the above installing complete, opencv still can't find.

> ROpenCVLite::isOpenCVInstalled()
[1] FALSE

and isOpenCVInstalled() showed FALSE

**Comment by sjmgarnier** [comment]
@Chengaowei Do you have multiple versions of Rtools installed?

**Comment by Chengaowei** [comment]
> 

@sjmgarnier 
![image](https://user-images.githubusercontent.com/45705105/179937832-75f1e3ba-067a-426b-8e95-b8323f7678c2.png)
Yeah, and I got an warnging message of rtools paths.

**Comment by Chengaowei** [comment]
@sjmgarnier  sorry for the missing info.
My R is 4.0.3. and  operating system is win 10.

**Comment by sjmgarnier** [comment]
@Chengaowei There is something strange about your install path. Can you walk me through how you installed ROpenCVLite? Did you specify a custom `path` parameter in `installOpenCV`?

**Comment by sjmgarnier** [comment]
@Chengaowei Also I recommend upgrading to the latest version of R (4.2.1) and RTools (4.2) unless you have very strong reasons to stick with 4.x.

**Comment by Chengaowei** [comment]
@sjmgarnier thanks very much! I reinstalling R(4.2.1), and solved this error.
