### ISSUE TITLE
openSUSE Tumbleweed (64bit) + R 3.4.1 + RStudio 1.0.153 installation problem

### ISSUE THREAD

**Issue by kk-1** [swarm-lab/ROpenCVLite#3]
I had installation problem in my 64 bit openSUSE system. I pasted the command line and the message below:
---------------------------------------
> devtools::install_github("swarm-lab/ROpenCVLite")
Downloading GitHub repo swarm-lab/ROpenCVLite@master
from URL https://api.github.com/repos/swarm-lab/ROpenCVLite/zipball/master
Installation failed: error in running command
---------------------------------------

Any idea?

Thanks
KK

**Comment by sjmgarnier** [comment]
@kk-1 Looks like it could be related to this: https://github.com/hadley/devtools/issues/638 & https://github.com/hadley/devtools/issues/406. Try `options(unzip = 'internal')` before installing.

**Comment by kk-1** [comment]
Thanks!
 "unzip" stuff worked but now another problem:
.
.
.
Looking for ccache - found (/usr/bin/ccache)
CMake Error at cmake/OpenCVCompilerOptions.cmake:21 (else):
  A duplicate ELSE command was found inside an IF block.
Call Stack (most recent call first):
  CMakeLists.txt:495 (include)

I got :
> cmake -version
cmake version 3.10.1

**Comment by sjmgarnier** [comment]
@kk-1 Can you try the latest version?

**Comment by kk-1** [comment]
I tried.
It seems because of nvidia gcc support (not for gcc7) it failed
I can not understand why nvidia software is dependent on the gcc version
Have the version 4.8 somewhere and I can set it with .R/makevars, but it sucks to change 
gcc version everythime.

Here is the important messages:
...
...
...
[  7%] Processing OpenCL kernels (core)
[  7%] Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o
In file included from /my_hd2/my_dir/my_prg/cuda-9.0/include/host_config.h:50:0,
                 from /my_hd2/my_dir/my_prg/cuda-9.0/include/cuda_runtime.h:78,
                 from <command-line>:0:
/my_hd2/my_dir/my_prg/cuda-9.0/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:208 (message):
  Error generating
  /tmp/RtmpIPnlvd/devtools2e82a6986ed/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o


make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:65: modules/core/CMakeFiles/cuda_compile.dir/src/cuda/cuda_compile_generated_gpu_mat.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1770: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...
...
...
...
[ 14%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledMisc.cpp.o
[ 14%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format.cc.o
[ 14%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledOutputFile.cpp.o
[ 14%] Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/wrappers.pb.cc.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledRgbaFile.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCode.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCodeAttribute.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVecAttribute.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVersion.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfWav.cpp.o
[ 15%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfZipCompressor.cpp.o
[ 15%] Linking CXX static library ../lib/libIlmImf.a
[ 17%] Linking CXX static library ../lib/liblibprotobuf.a
[ 17%] Built target IlmImf
[ 17%] Built target libprotobuf
make: *** [Makefile:163: all] Error 2
ERROR: configuration failed for package ‘ROpenCVLite’
* removing ‘/home/kemal/R/x86_64-suse-linux-gnu-library/3.4/ROpenCVLite’
Installation failed: Command failed (1)

**Comment by sjmgarnier** [comment]
Alternatively, I could deactivate compiling with CUDA if gcc's version is greater than 6.

**Comment by kk-1** [comment]
I guess it will be better to remove CUDA dependency, otherwise, people with AMD graphics card will not be able to use ROpenCVLite. How about people with AMD CPUs? is icc required dep?

**Comment by sjmgarnier** [comment]
@kk-1 Cmake already takes care of deactivating CUDA and ICC support on machines that can't support them. In your case, we would need to tell Cmake to deactivate CUDA support if CUDA is installed but GCC's version is superior to 6. It shouldn't be too difficult (famous last words).

**Comment by kk-1** [comment]
Setting gcc to custom 4.8 in .R/makevars did not work.
Is there any other way to set alternative gcc in the following R command line?
options(unzip = 'internal');devtools::install_github("swarm-lab/ROpenCVLite")

**Comment by sjmgarnier** [comment]
I believe this is because Cmake ignores R-specific things when compiling OpenCV. It should be possible to pass an argument to the configure file specifying the location of an alternative gcc, and then have the configure pass this to Cmake. I don't have much time today, but I'll explore this option.

**Comment by kk-1** [comment]
I was able to set the gcc to my custom ver4.8 with:
options(unzip = 'internal');
devtools::install_github("swarm-lab/ROpenCVLite", args = c('--configure-vars="CC=gcc-4.8 CXX=g++-4.8"'))

But this time these two errors:
/usr/include/bits/floatn.h(61): error: invalid argument to attribute "__mode__"
/usr/include/bits/floatn.h(73): error: identifier "__float128" is undefined
...
...
...
2 errors detected in the compilation of "/tmp/tmpxft_00005793_00000000-13_gpu_mat.compute_70.cpp1.ii".
CMake Error at cuda_compile_generated_gpu_mat.cu.o.cmake:266 (message):
  Error generating file
  /tmp/RtmpsuJVzL/devtools43e72e327fd9/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build/modules/core/CMakeFiles/cuda_compile.dir/src/cuda/./cuda_compile_generated_gpu_mat.cu.o

anyway I am so tired.
CUDA was better in the past....

**Comment by sjmgarnier** [comment]
This goes beyond my abilities I'm afraid. Why use gcc 4.8 if CUDA is compatible with gcc 6?

**Comment by sjmgarnier** [comment]
BTW, do you mind opening a specific issue for the CUDA thing since it's not related to the original problem? Thanks. I will close this issue in the meantime.
