### ISSUE TITLE
Problems installing ROpenCVLite package on Windows 10 locally,      display() giving errors on Posit Cloud

### ISSUE THREAD

**Issue by pcofoche** [swarm-lab/ROpenCVLite#40]
I have been having an issue with installing ROpenCVLite on my Windows 10 computer for several months. While the installation runs successfully, on Posit Cloud, it gives an error on the local machine and it has prevented me from using the package. Could you please help to look into this?

Many thanks,
Paul

Here is my session info:

"R version 4.3.1 (2023-06-16 ucrt)"
"ROpenCVLite_4.80.1"
 - Cmake version: not installed
 - Rtools version (Windows only): both "rtools42" and "rtools43" are installed on my system

Here is the installation code run:
install.packages("ROpenCVLite")
ROpenCVLite::installOpenCV()

Here is the error obtained below (also attached):
[ 73%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/degeneracy.cpp.obj
C:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: internal error: aborting at ../../binutils-2.40/ld/ldlang.c:527 in compare_section
C:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: please report this bug
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/dls_solver.cpp.obj
collect2.exe: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:307: bin/libopencv_videoio480.dll] Error 1
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/essential_solver.cpp.obj
make[1]: *** [CMakeFiles/Makefile2:2946: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 74%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv_1x1_fast_spv.cpp.obj
[ 74%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv_depthwise_3x3_spv.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/estimator.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/fundamental_solver.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/gamma_values.cpp.obj
[ 74%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv_depthwise_spv.cpp.obj
[ 74%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/conv_implicit_gemm_spv.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/homography_solver.cpp.obj
[ 74%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/gemm_spv.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/local_optimization.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/pnp_solver.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/quality.cpp.obj
[ 74%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/ransac_solvers.cpp.obj
[ 75%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/shader/spv_shader.cpp.obj
[ 75%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/sampler.cpp.obj
[ 75%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/termination.cpp.obj
[ 75%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/buffer.cpp.obj
[ 75%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/command.cpp.obj
[ 76%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/src/usac/utils.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/context.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/fence.cpp.obj
[ 76%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/opencl_kernels_calib3d.cpp.obj
[ 76%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/undistort.avx2.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/internal.cpp.obj
[ 76%] Building RC object modules/calib3d/CMakeFiles/opencv_calib3d.dir/vs_version.rc.obj
[ 76%] Building CXX object modules/calib3d/CMakeFiles/opencv_calib3d.dir/opencv_calib3d_main.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_base.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_conv.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/op_matmul.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/pipeline.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/src/tensor.cpp.obj
[ 76%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_functions.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/src/vkcom/vulkan/vk_loader.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencl_kernels_dnn.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_block.avx.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_depthwise.avx.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_winograd_f63.avx.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx2.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx2.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_block.avx2.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_depthwise.avx2.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/cpu_kernels/conv_winograd_f63.avx2.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/layers/layers_common.avx512_skx.cpp.obj
[ 77%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/int8layers/layers_common.avx512_skx.cpp.obj
[ 78%] Building RC object modules/dnn/CMakeFiles/opencv_dnn.dir/vs_version.rc.obj
[ 78%] Building CXX object modules/dnn/CMakeFiles/opencv_dnn.dir/opencv_dnn_main.cpp.obj
[ 78%] Linking CXX shared library ../../bin/libopencv_dnn480.dll
[ 78%] Linking CXX shared library ../../bin/libopencv_calib3d480.dll
[ 78%] Built target opencv_calib3d
[ 78%] Built target opencv_dnn
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/c/Users/PCOfoche/AppData/Local/Temp/RtmpmEnpaA/opencv-4.8.0/build64'
make: Entering directory '/c/Users/PCOfoche/AppData/Local/Temp/RtmpmEnpaA/opencv-4.8.0/build64'
[  0%] Built target opencv_dnn_plugins
[  0%] Built target opencv_highgui_plugins
Consolidate compiler generated dependencies of target jsimd
[  3%] Built target jsimd
Consolidate compiler generated dependencies of target libopenjp2
[  5%] Built target libopenjp2
[  5%] Built target opencv_videoio_plugins
Consolidate compiler generated dependencies of target zlib
[  7%] Built target zlib
Consolidate compiler generated dependencies of target opencv_core
[ 16%] Built target opencv_core
Consolidate compiler generated dependencies of target opencv_flann
[ 17%] Built target opencv_flann
Consolidate compiler generated dependencies of target opencv_imgproc
[ 24%] Built target opencv_imgproc
Consolidate compiler generated dependencies of target opencv_ml
[ 25%] Built target opencv_ml
Consolidate compiler generated dependencies of target opencv_photo
[ 26%] Built target opencv_photo
Consolidate compiler generated dependencies of target libprotobuf
[ 29%] Built target libprotobuf
Consolidate compiler generated dependencies of target opencv_dnn
[ 41%] Built target opencv_dnn
Consolidate compiler generated dependencies of target opencv_features2d
[ 43%] Built target opencv_features2d
Consolidate compiler generated dependencies of target libjpeg-turbo
[ 47%] Built target libjpeg-turbo
Consolidate compiler generated dependencies of target libtiff
[ 51%] Built target libtiff
Consolidate compiler generated dependencies of target libwebp
[ 60%] Built target libwebp
Consolidate compiler generated dependencies of target libpng
[ 61%] Built target libpng
Consolidate compiler generated dependencies of target IlmImf
[ 69%] Built target IlmImf
Consolidate compiler generated dependencies of target opencv_imgcodecs
[ 71%] Built target opencv_imgcodecs
Consolidate compiler generated dependencies of target opencv_videoio
[ 71%] Linking CXX shared library ../../bin/libopencv_videoio480.dll
C:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: internal error: aborting at ../../binutils-2.40/ld/ldlang.c:527 in compare_section
C:\rtools43\x86_64-w64-mingw32.static.posix\bin/ld.exe: please report this bug
collect2.exe: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:307: bin/libopencv_videoio480.dll] Error 1
make[1]: *** [CMakeFiles/Makefile2:2946: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/c/Users/PCOfoche/AppData/Local/Temp/RtmpmEnpaA/opencv-4.8.0/build64'
[1] FALSE

![Error](https://github.com/swarm-lab/ROpenCVLite/assets/27927074/d0c5b139-4701-4b27-b96f-81e8314a8645)

display() also gives errors when the code is run on Posit Cloud, as shown below:

library(Rvision)
balloon <- image(system.file("sample_img/balloon1.png", package = "Rvision"))
display(balloon, height = nrow(balloon), width = ncol(balloon))

> library(Rvision)
> balloon <- image(system.file("sample_img/balloon1.png", package = "Rvision"))
> display(balloon, height = nrow(balloon), width = ncol(balloon))
Error: OpenCV(4.8.0) /tmp/RtmpHxPqVd/opencv-4.8.0/modules/highgui/src/window.cpp:1272: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'

Could you please help?

Thank you,
Paul

![Error2](https://github.com/swarm-lab/ROpenCVLite/assets/27927074/37124dea-1194-4239-97da-d3dad726a8b2)

############################################################################################################################################################################################################################################################################################################

**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior

**Expected behavior**

**Screenshots**

**Computer (please complete the following information):**
 - Operating system: [e.g. MacOS]
 - Version [e.g. 11.2.1]

**R (please complete the following information):**
 - R version: [e.g. 4.0.4]
 - ROpenCVLite version: [e.g. 4.50.0]
 - Cmake version: [e.g. 3.19.1]
 - Rtools version (Windows only): [e.g. 4.0]

**Additional context**

**Comment by sjmgarnier** [comment]
@pcofoche Thanks for reporting the two problems. For future reference, it's better to report each problem in separate issues (actually, one of the problems is linked to Rvision and should have been reported on the corresponding repository). This makes tracking progress on separate errors simpler for the developers (in this case, me). 

Let's start with the easy one: it is normal that `display()` does NOT work on Posit Cloud (or on any RStudio Server for that matter). The reason is that `display()` requires access to the graphical user interface (GUI) of the server which is not possible through Posit Cloud and RStudio Server. These are essentially fancy web servers and they cannot access the GUI of the system they are running on (if any is available – the Posit Cloud server probably has none). You can use the `plot()` function instead on such servers. However, it is considerably slower than `display()` when it is available and won't be suitable for applications requiring live display. 

Regarding the compilation problem with ROpenCVLite, the error message suggests that there was an earlier error message that was not included in your post. Could you please include the entire output of the compilation process if you can? That would be helpful to find the source of the problem. Thanks.

**Comment by sjmgarnier** [comment]
@pcofoche The error on the second machine is due to Cmake not being found on the PATH. You may need to log out and back in (or maybe even reboot) for your session to read the new path correctly.

**Comment by pcofoche** [comment]
Thank you. I have restarted System 2, but this error appears.

[cid:48b1bfca-052f-46e9-a51e-9d69f5ef9013]
________________________________
