### ISSUE TITLE
Can't find object 'rtools_path'

### ISSUE THREAD

**Issue by Monodia97** [swarm-lab/ROpenCVLite#47]
> library(ROpenCVLite)
OpenCV is not installed on this system. Would you like to install it now? This will take several minutes. 

1: yes
2: no

Selection: 1
Error: package or namespace load failed for 'ROpenCVLite':
 .onAttach failed in attachNamespace() for 'ROpenCVLite', details:
  call: get(name, envir = cache)
  error: object 'rtools_path' not found

But I set the environment variables as below
![image](https://github.com/swarm-lab/ROpenCVLite/assets/80382483/cd025804-8d0e-464e-a4a4-52245a43dd0e)

**Comment by sjmgarnier** [comment]
@Monodia97 Can you please answer the following questions?

---

**Computer (please complete the following information):**
 - Operating system: [e.g. MacOS]
 - Version [e.g. 11.2.1]

**R (please complete the following information):**
 - R version: [e.g. 4.0.4]
 - ROpenCVLite version: [e.g. 4.50.0]
 - Cmake version: [e.g. 3.19.1]
 - Rtools version (Windows only): [e.g. 4.0]

---

In addition, what is the output of `utils::shortPathName(pkgbuild::rtools_path()[1])`?

**Comment by Monodia97** [comment]
@sjmgarnier 
**Computer (please complete the following information):**

- Operating system: Windows 10
- Version: 22H2

**R (please complete the following information):**

- R version: 4.4.0
- ROpenCVLite version: 4.90.1
- Cmake version: 3.28.1
- Rtools version (Windows only): 4.3

the output
> utils::shortPathName(pkgbuild::rtools_path()[1])
Error in get(name, envir = cache) : object 'rtools_path' not found

**Comment by sjmgarnier** [comment]
@Monodia97 It looks like the error is related to this problem in older versions of pkgbuild: https://github.com/r-lib/pkgbuild/issues/74. Try running `pkgbuild::find_rtools()` before trying again.

**Comment by Monodia97** [comment]
@sjmgarnier  ok and the output is below
> pkgbuild::find_rtools()
[1] FALSE
> utils::shortPathName(pkgbuild::rtools_path()[1])
Error in get(name, envir = cache) : object 'rtools_path' not found

**Comment by sjmgarnier** [comment]
@Monodia97 What does `has_rtools(debug = TRUE)` return?

**Comment by Monodia97** [comment]
@sjmgarnier FALSE
> has_rtools(debug = TRUE)
[1] FALSE

**Comment by sjmgarnier** [comment]
@Monodia97 Then it means that Rtools is either not installed, or installed somewhere R cannot find.

**Comment by Monodia97** [comment]
@sjmgarnier  emm...What should I do to resolve it? Reinstall Rtools?

**Comment by sjmgarnier** [comment]
@Monodia97 Possibly. Where is it installed at the moment?

**Comment by Monodia97** [comment]
@sjmgarnier  In C:\rtools43. And R is in D:\R\R-4.4.0

**Comment by Monodia97** [comment]
@sjmgarnier  uninstalled R 4.4.0 and installed R 4.3.3. Now it is solved. Thank you.

**Comment by sjmgarnier** [comment]
@Monodia97 Oh, I just noticed the mismatch between the version of R and Rtools. With R 4.4, you need to install Rtools 4.4 (https://cran.r-project.org/bin/windows/Rtools/). Your R and Rtools versions must always match.

**Comment by Monodia97** [comment]
@sjmgarnier  Ok, thank you for your help
