### ISSUE TITLE
Win Installation failed: Command failed (1)

### ISSUE THREAD

**Issue by cybermascot** [swarm-lab/ROpenCVLite#5]
HI,
I am recieving this error during installation,
************************************************************************************************************
CMakeFiles/opencv_python2.dir/objects.a(cv2.cpp.obj):cv2.cpp:(.text$initcv2+0x24c6): undefined reference to `__imp_Py_InitModule4'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [lib/cv2.pyd] Error 1
make[1]: *** [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make: *** [all] Error 2
Warning: running command 'sh ./configure.win' had status 2
ERROR: configuration failed for package 'ROpenCVLite'
* removing 'C:/Users/asadk/Documents/R/win-library/3.4/ROpenCVLite'
Installation failed: Command failed (1)
************************************************************************************************************
any solution please
Thanks
Asad

**Comment by ThaiseRF** [comment]
Hey! So, I had a similar error during Win installation.


`[ 39%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/modules/core/include: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/modules/core/src: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64/modules/core: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/3rdparty/zlib: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/build64/3rdparty/zlib: No such file or directory
gcc: error: Freitas/AppData/Local/Temp/RtmpMXPILz/devtools29885a8c1984/swarm-lab-ROpenCVLite-55af572/inst/tmp/opencv-3.4.0/3rdparty/include/opencl/1.2: No such file or directory
C:\Rtools\mingw_64\bin\windres.exe: preprocessing failed.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfRgbaFile.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfRgbaYca.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfRleCompressor.cpp.obj
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfScanLineInputFile.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStandardAttributes.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStdIO.cpp.obj
[ 39%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStringAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfStringVectorAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTestFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfThreading.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTileDescriptionAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTileOffsets.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledInputFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledMisc.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledOutputFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTiledRgbaFile.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCode.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfTimeCodeAttribute.cpp.obj
[ 40%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVecAttribute.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfVersion.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfWav.cpp.obj
[ 41%] Building CXX object 3rdparty/openexr/CMakeFiles/IlmImf.dir/IlmImf/ImfZipCompressor.cpp.obj
[ 41%] Linking CXX static library ../lib/libIlmImf.a
make[1]: *** Waiting for unfinished jobs....
[ 41%] Built target IlmImf
make: *** [all] Error 2
Warning: command execution 'sh ./configure.win'  status 2
ERROR: configuration failed for package 'ROpenCVLite'`

Don't know what I did wrong.
Any help?
Thanks!!
Thaise.

**Comment by sjmgarnier** [comment]
@ThaiseRF This is a different error. Can you please open a separate thread, and include your operating system, R and RTools versions, and the command line you used to install ROpenCVLite? Thanks.
