### ISSUE TITLE
installation failed gcc error

### ISSUE THREAD

**Issue by dcornet** [swarm-lab/ROpenCVLite#8]
Hi,

I've got the following error while trying to install ROpenCVLite:

```
[ 42%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/modules/core/include: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/modules/core/src: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64/modules/core: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/3rdparty/zlib: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64/3rdparty/zlib: No such file or directory
gcc: error: CORNET/AppData/Local/Temp/RtmpsRyiOE/devtools231c66bb2aa4/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/3rdparty/include/opencl/1.2: No such file or directory
C:\Rtools\mingw_64\bin\windres.exe: preprocessing failed.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2
Warning: l'exécution de la commande 'sh ./configure.win' renvoie un statut 2
ERROR: configuration failed for package 'ROpenCVLite'
* removing 'C:/Program Files/R/R-3.4.1/library/ROpenCVLite'
Installation failed: Command failed (1)
```

I'm using windows 7, R3.4.1 and RStudio1.1.423
I've installed Rtools3.3.0.1959, Cmake3.10.3 and OpenCV3.4.1
Thanks in advance for help.

d

**Comment by sjmgarnier** [comment]
@dcornet This looks like the same problem as #6. The mingw/gcc installation does not handle well spaces in the path (there is a space between "Program" and "Files" in your installation folder). I'm not sure how to fix this yet. In the meantime, you can try installing the package in a different location without spaces in the path.

**Comment by dcornet** [comment]
Thanks @sjmgarnier. I've reinstalled Rtools, Cmake and opencv in repository without space in the path. Then I used

> withr::with_libpaths(new = "D:/Rlib", install_github("swarm-lab/ROpenCVLite"))

to install library in a repository without space in the path. But I still get the same error:

> [ 42%] Building RC object modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/modules/core/include: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/modules/core/src: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64/modules/core: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/3rdparty/zlib: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/build64/3rdparty/zlib: No such file or directory
> gcc: error: CORNET/AppData/Local/Temp/RtmpaOawBW/devtools2ab0509d3396/swarm-lab-ROpenCVLite-b9fcf19/inst/tmp/opencv-3.4.1/3rdparty/include/opencl/1.2: No such file or directory
> C:\Rtools\mingw_64\bin\windres.exe: preprocessing failed.
> make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/vs_version.rc.obj] Error 1
> make[2]: *** Waiting for unfinished jobs....
> make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
> make: *** [all] Error 2
> Warning: l'exécution de la commande 'sh ./configure.win' renvoie un statut 2
> ERROR: configuration failed for package 'ROpenCVLite'
> * removing 'D:/Rlib/ROpenCVLite'
> Installation failed: Command failed (1)

Any help would be appreciate.

**Comment by sjmgarnier** [comment]
@dcornet Is there a space in your username (i.e. before "CORNET/AppData/..."? It looks like gcc cannot find the location of the Temp folder.

**Comment by sjmgarnier** [comment]
@dcornet Yes, this is what happened in #6. I don't work on Windows, so I haven't investigated this issue much.

**Comment by dcornet** [comment]
I found a solution.
I reinstalled R, Rstudio, cmake and Rtools to folder acessed path without space (e.g. D:/)
Then I changed the path of the [TEMP ](acessed path without space (e.g. D:/))files to folder acessed path without space (e.g. D:/TEMP)
Finally I installed ROpenCVLite again and everything get fine.
